# Rustfmt configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Function formatting
fn_params_layout = "Tall"

# Misc formatting
match_block_trailing_comma = true

# Use field shorthand if possible
use_field_init_shorthand = true

# Chain formatting
chain_width = 60
single_line_if_else_max_width = 50

# Import reordering
reorder_imports = true
reorder_modules = true