name: Release and Update Homebrew
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew Formula
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          TARBALL_URL="https://github.com/${{ github.repository }}/archive/refs/tags/v${VERSION}.tar.gz"
          SHA256=$(curl -sL $TARBALL_URL | shasum -a 256 | cut -d' ' -f1)

          # Homebrew リポジトリをクローン
          git clone https://${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/mmrakt/homebrew-pretty-git-ui.git homebrew-tap
          cd homebrew-tap

          # Formulaを更新
          sed -i "s|url \".*\"|url \"${TARBALL_URL}\"|" Formula/pretty-git-ui.rb
          sed -i "s/sha256 \".*\"/sha256 \"${SHA256}\"/" Formula/pretty-git-ui.rb

          # コミット・プッシュ
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Formula/pretty-git-ui.rb
          git commit -m "Update formula to v${VERSION}"
          git push origin main
